### ISSUE TITLE
Which columns, labels and etc Trello should have?

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/Guidebook#12]
If not Trello, GitHub + Waffle.io

**Comment by filipeximenes** [comment]
Here's how I've been doing it
- Backlog (features)
- Bugs 
- Sprint
- Review
- Done

**Comment by filipeximenes** [comment]
Adding Documents column:

- Documents
- Backlog (features)
- Bugs
- Sprint
- Review
- Done
