### ISSUE TITLE
Development checklist

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/Guidebook#38]
- Read specs
- Develop feature/write automated tests
- Read specs again reviewing if everything is done
- Manually QA what was done
- Run tests
- Start PR
- Review your own code
- Submit PR

**Comment by fjsj** [comment]
- Read specs
- Develop feature/write automated tests
- Read specs again reviewing if everything is done
- Manually QA what was done
- Merge develop or target branch into feature branch
- Run tests
- Start PR
- Review your own code
- Submit PR
